# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQn1u-pUEkui9hN19lVa12WvneHYmC-H
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder

# Load and clean dataset
df = pd.read_csv("1- mental-illnesses-prevalence.csv")
df = df.rename(columns={
    df.columns[3]: "Schizophrenia",
    df.columns[4]: "Depression",
    df.columns[5]: "Anxiety",
    df.columns[6]: "Bipolar",
    df.columns[7]: "Eating_Disorder"
})
df["Most_Prevalent_Disorder"] = df[["Schizophrenia", "Depression", "Anxiety", "Bipolar", "Eating_Disorder"]].idxmax(axis=1)
df["Lifeloom_Risk_Score"] = df[["Schizophrenia", "Depression", "Anxiety", "Bipolar", "Eating_Disorder"]].sum(axis=1)

# Encode countries
le = LabelEncoder()
df["Entity_Code"] = le.fit_transform(df["Entity"])

# Train model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(df[["Entity_Code", "Year"]], df["Lifeloom_Risk_Score"])

# Streamlit UI
st.set_page_config(page_title="Lifeloom Mental Health Analyzer", layout="wide")
st.title("🧠 Lifeloom - Mental Health Risk Analyzer")

# User Inputs
country = st.selectbox("Select a Country", sorted(df["Entity"].unique()))
year = st.slider("Select Year", int(df["Year"].min()), int(df["Year"].max()), 2020)

# Predict
encoded_country = le.transform([country])[0]
input_df = pd.DataFrame([[encoded_country, year]], columns=["Entity_Code", "Year"])
predicted_score = model.predict(input_df)[0]

# Show Prediction
st.metric("Predicted Lifeloom Risk Score", f"{predicted_score:.2f}")

# Show Prevalent Disorder
row = df[(df["Entity"] == country) & (df["Year"] == year)]
if not row.empty:
    prevalent = row.iloc[0]["Most_Prevalent_Disorder"]
    st.markdown(f"**Most prevalent disorder in {country} ({year}):** `{prevalent}`")
else:
    st.warning("No data available for selected country and year.")

# Line Plot
st.subheader("📊 Mental Illness Trends Over Time")
plot_df = df[df["Entity"] == country]

fig, ax = plt.subplots(figsize=(10, 5))
for disorder in ["Schizophrenia", "Depression", "Anxiety", "Bipolar", "Eating_Disorder"]:
    ax.plot(plot_df["Year"], plot_df[disorder], label=disorder)
ax.set_title(f"Trend of Mental Illnesses in {country}")
ax.set_xlabel("Year")
ax.set_ylabel("Prevalence (% of population)")
ax.legend()
st.pyplot(fig)

# CBT Tips
st.subheader("💡 Mental Health Self-Care Tip (CBT Style)")
tips = {
    "Depression": "📝 Keep a daily gratitude journal to focus on positives.",
    "Anxiety": "🧘‍♀️ Practice 4-7-8 breathing technique for 2 minutes.",
    "Schizophrenia": "📅 Stick to a consistent daily routine.",
    "Bipolar": "📊 Track your mood and sleep patterns regularly.",
    "Eating_Disorder": "🥗 Try mindful eating and be kind to yourself."
}
if not row.empty:
    tip = tips.get(prevalent, "🧠 Take care of your mental health. You are not alone.")
    st.info(tip)

# Footer
st.markdown("---")
st.caption("Built with ❤️ by Manogna | Lifeloom 2025")